/**
 * DGTAuthenticateButton.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface j_org_robovm_pods_digits_DGTAuthenticateButton : UIButton 

@end
